name: Sync to gitee
on:
  workflow_dispatch:  # 允许手动触发

jobs:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/gitgordon85'    			
          dst: 'gitee/gordon85'   
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}  
          dst_token:  ${{ secrets.GITEE_TOKEN }}  
          force_update: true
          static_list: "Gordon85_IPTV"
          account_type: user   		
          debug: true
